### ISSUE TITLE
RMQValues file has missing return value of RMQDouble

### ISSUE THREAD

**Issue by gamzeylmz** [rabbitmq/rabbitmq-objc-client#105]
RMQDouble has "floatValue" property which is double. However this float value property is not assigned at all. Besides, there's a doubleValue property which is not accessible from outside, in .m file. Generally its implemented. 

Then, in log it seems as: 

> @"object": <RMQDouble: 0x13e20de00
>                         doubleValue = 39.9002402
>                         floatValue = 0>,

And cannot be get its exact double value.

**Comment by camelpunch** [comment]
@gamzeylmz does the above commit solve your problem?

**Comment by gamzeylmz** [comment]
Yeah, we can accept is as solution. I didn't commit here but did the same.

**Comment by michaelklishin** [comment]
@gamzeylmz thank you for reporting back!
