### ISSUE TITLE
RMQBasicConsume can't add arguments to a consumer

### ISSUE THREAD

**Issue by timhonders** [rabbitmq/rabbitmq-objc-client#106]
It seems it's not possible to set the arguments to the RMQBasicConsume.

In the RMQMethods+Convenience.m 
the implementation RMQBasicConsume initWithQueue sets the arguments with a new empty RMQTable 

[https://github.com/rabbitmq/rabbitmq-objc-client/blob/121a96b20618f58c431eb898ed983d283b9f046b/RMQClient/RMQMethods%2BConvenience.m](url)

**Comment by michaelklishin** [comment]
Yes. It's a rarely used feature so we left it out of the original implementation. Thanks for pointing it out.

**Comment by timhonders** [comment]
We want to use it for x-priority on the consumer, so a mobile phone with a bad connection will receive messages with a new connection when the old one isn't closed by the server.

**Comment by michaelklishin** [comment]
@timhonders that I'd recommend using [a lower heartbeat timeout value](http://www.rabbitmq.com/heartbeats.html) instead, e.g. 6-8 seconds.

**Comment by michaelklishin** [comment]
@timhonders also, if it's a matter of adding a single convenience method, feel free to look into a pull request. Community contributions have a pretty high priority for our team :)

**Comment by timhonders** [comment]
Ok i wil give it a try :)

**Comment by timhonders** [comment]
Added a pull request

[https://github.com/rabbitmq/rabbitmq-objc-client/pull/107](url)

**Comment by michaelklishin** [comment]
@timhonders it's in, thank you!
