### ISSUE TITLE
JKVValue Not compatible with watch os

### ISSUE THREAD

**Issue by lettierimarco** [rabbitmq/rabbitmq-objc-client#120]
[!] The platform of the target `WatchKit Extension` (watchOS 2.0) is not compatible with `JKVValue (1.3.2)`, which does not support `watchos`.

**Comment by michaelklishin** [comment]
Unless there is a JKValue version that is compatible, this is an issue for JKValue itself. So, is there a compatible version we can try depending on?

Needless to say the last environment where we expected this client to be used is WatchOS :)

**Comment by lettierimarco** [comment]
I haven't found a jkvalue github or issue tracker

**Comment by michaelklishin** [comment]
Well, take a look at `Cartfile` and you'll find https://github.com/jeffh/JKVValue references there ;)
