### ISSUE TITLE
Support for Swift Package Manager

### ISSUE THREAD

**Issue by gperdomor** [rabbitmq/rabbitmq-objc-client#134]
Please add support for SPM :D

**Comment by michaelklishin** [comment]
I'm not sure how common it is to distributed Objective-C frameworks via SPM but some research suggests it is certainly possible.

**Comment by cliapis** [comment]
Hi,
Do you have any plans to support a native Swift implementation? 
Server side Swift cannot use objective c code.

Thank you.

**Comment by michaelklishin** [comment]
@cliapis please ask questions on rabbitmq-users. There are plans but our team is very small and it's never a priority. We'd be happy to provide guidance to someone who'd be interested in developing a Swift client.

**Comment by michaelklishin** [comment]
A new round of research suggests that even if possible, distributing Objective-C code via SPM is a major pain. Our dependencies (e.g. CocoaAsyncSocket) do not provide SPM manifests, which doesn't help.

I'm afraid this is a no-go given how much time I have for this library. That time would be better spent working on a native Swift client ;)

**Comment by tadman** [comment]
It's worth noting an alternative is to use a [STOMP client](https://github.com/WrathChaos/StompClientLib) on a STOMP-enabled RabbitMQ server. That's a plugin that comes with, it just needs to be enabled.

While not as full-featured as a proper AMQP connection, it's better than nothing.
