### ISSUE TITLE
IPv4 preference can cause handshake timeouts on cellular networks

### ISSUE THREAD

**Issue by benvigier** [rabbitmq/rabbitmq-objc-client#138]
I have tested RMQClient over T-Mobile LTE on multiple iPhone 6S and earlier models and consistently get a handshake timeout when on LTE (while it works perfectly well over Wifi), when running the demo code in the documentation.
After researching the issue extensively, it seems to be caused by some 4G networks IPv4 vs. IPv6 configurations. 

Inserting the following line in RMQTCPSocketTransport.initWithHost() fixes the issue:

`self.socket.IPv4PreferredOverIPv6 = NO;`

Happy to provide more info and video illustrating the issue if needed.

**Comment by michaelklishin** [comment]
@benvigier thank you for doing all the hard work. Please submit a PR that makes this configurable for starters. I don't have much data or iOS development experience to make an informed decision about what should be the default but open to changing the default as well. Thank you.

**Comment by michaelklishin** [comment]
A very quick research reveals that [some have been recommending preferring IPv6](https://github.com/robbiehanson/XMPPFramework/issues/718#issuecomment-225107691) for a couple of years now and it was never a problem in their app review process. So perhaps changing the default is a good idea.

**Comment by benvigier** [comment]
Great way to fix it.
Thanks Michael.

PS: Sorry for not submitting a PR, I don’t have the project properly set-up in GitHub to do so.
