### ISSUE TITLE
vhost with multiple slashes

### ISSUE THREAD

**Issue by GaoShin** [rabbitmq/rabbitmq-objc-client#146]
I have tried vhost with one slash and no slash and both work fine.But if the vhost contains more than 2 slashes it will never work.Here is an example:
amqp://test:test@192.168.1.3/%2fpath1%2fpath2

And then I find out that the problem is the method in RMQURI.m:
+ (nullable instancetype)parse:(nonnull NSString *)uri error:(NSError * _Nullable * _Nullable)error;
Even if I replace the path component / with %2f,the result is same.
I don't know how to really fix it and I just bypass this method to temporarily 'fix' for me.

**Comment by michaelklishin** [comment]
What does "never work" mean specifically? The URI parsing fails? Something else?

**Comment by GaoShin** [comment]
This method will return nil:
(nullable instancetype)parse:(nonnull NSString *)uri error:(NSError * _Nullable * _Nullable)error;
And I can see the error log from Xcode:

> TestRabbitMQ[884:167898] Received connection: <RMQConnection: 0x283be4780> failedToConnectWithError: Error Domain=GCDAsyncSocketErrorDomain Code=2 "Invalid host parameter (nil or ""). Should be a domain name or IP address string." UserInfo={NSLocalizedDescription=Invalid host parameter (nil or ""). Should be a domain name or IP address string.}
