### ISSUE TITLE
Bump version number for Cocoapods and Carthage

### ISSUE THREAD

**Issue by mattbradbury** [rabbitmq/rabbitmq-objc-client#148]

**Comment by mattbradbury** [comment]
Master branch builds for OSX just fine with both Cocoa and Carthage, just needs a little admin love with the version numbers and tags

**Comment by michaelklishin** [comment]
What problem would that solve?

**Comment by mattbradbury** [comment]
I can build by using git commands in the carthage file.  Carthage and Cocoapods need to use the git release tags to properly download the current releases

**Comment by michaelklishin** [comment]
So you are asking for a new release?

**Comment by michaelklishin** [comment]
Carthage can use Git commits, e.g.

```
github "rabbitmq/rabbitmq-objc-client" "master"
```

should work.

A new release will be out once #146 is addressed.

**Comment by michaelklishin** [comment]
I think we are ready to produce a new release.

**Comment by grsteffens** [comment]
Any update or ETA on this? I tried pulling in the latest changes by pointing my Cocoapods spec to the master branch, however it appears now conforming to the `RMQConnectionDelegate` causes a linker issue? If I remove my implementation of this delegate's methods, all is well again.

**Comment by michaelklishin** [comment]
I can look into it in the next couple of days.

**Comment by michaelklishin** [comment]
I cannot comment on "a linker issue". This issue is about producing a new release. That said, I think we should produce an RC first and try it out e.g. with rabbitmq/rabbitmq-tutorials.

**Comment by michaelklishin** [comment]
I experimented with this today in hopes to produce an RC. Unfortunately I cannot finish this today and won't be around tomorrow but this is my priority number one for Friday.

**Comment by michaelklishin** [comment]
I found a bug in client-initiated `connection.close` handling that got revealed by a Swift 5 upgrade. Will produce an RC1 after fixing it.

**Comment by grsteffens** [comment]
Hi @michaelklishin, any update on the RC1?

**Comment by michaelklishin** [comment]
I'm fighting `pod trunk push`, looks like the only outstanding issue is that my user doesn't have the permissions. I've contacted the original author and trying to sign in using our team account.

**Comment by michaelklishin** [comment]
Looks like we will have to go through the pod dispute/claim process to regain push permissions :(

**Comment by michaelklishin** [comment]
`0.11.0-rc1` [is up on cocoapods.org](https://cocoapods.org/pods/RMQClient).

**Comment by michaelklishin** [comment]
See #166 for GA release. We only need some feedback, tutorial updates and a change log. @grsteffens your feedback would be most welcome :)

**Comment by grsteffens** [comment]
Implementing now, I will follow up on #166 with my feedback. Thanks @michaelklishin !
