### ISSUE TITLE
Creating a queue with a server-generated name

### ISSUE THREAD

**Issue by simba909** [rabbitmq/rabbitmq-objc-client#149]
I’ve tried reading through the source, but I can’t seem to find a way to create queues with server-generated names. Is this supported? If not, is support for it on the roadmap? :)

I would gladly help out with a PR if I could, but unfortunately I might not have time for that anytime soon.

**Comment by michaelklishin** [comment]
This client chose to [generate queue names](https://github.com/rabbitmq/rabbitmq-objc-client/blob/master/RMQClient/RMQAllocatedChannel.m#L526) on its own when an empty string is passed. That's typically sufficient. We may revisit this at some point but it's not meaningfully different.

Bunny has been generating consumer tags for close to a decade and no one seems to mind, for example, even though technically the broker can do it.

**Comment by michaelklishin** [comment]
Integration tests [such as these](https://github.com/rabbitmq/rabbitmq-objc-client/blob/master/RMQClientIntegrationTests/QueueIntegrationTest.swift#L77) is the best source of information on API usage at the moment, and it will continue for a while as this client's API changes slightly to make it easier to use from Swift and I revisit some minor design decisions for `0.11.0` and beyond.
