### ISSUE TITLE
afterCofirmed called with no ack/nack

### ISSUE THREAD

**Issue by SimonErm** [rabbitmq/rabbitmq-objc-client#168]
Hey,
I use publisher confirms by using:
```
 channel.confirmSelect();
 channel.afterConfirmed{ (acked, nacked) in
            Log.info?.value(acked.count);
            Log.info?.value(nacked.count);
        }
```
but afterConfirmed is called with no ack/nack.
Is this a bug?
Maybe related: #157

**Comment by michaelklishin** [comment]
I don't see how that is possible given [its type signature](https://github.com/rabbitmq/rabbitmq-objc-client/blob/5a845807072c0112168d12dfd6449867764c10a8/RMQClient/RMQChannel.h#L94). Sorry but I cannot suggest much without a way to reproduce.

**Comment by michaelklishin** [comment]
#157 as I observed it could be relevant if both sets were empty. Now that I think of it, it could violate some tests' assumptions but it's not an impossible scenario: there can be no acks or nacks delivered at a certain point in time. Why would `afterConfirmed` be invoked so early (or so late), I'm not sure. We need at least some steps to reproduce or clues from code analysis.

**Comment by SimonErm** [comment]
Yes, both are empty but there should be an ack because the message is delivered. I am going to provide a sample repo the next days.

**Comment by michaelklishin** [comment]
@SimonErm thank you. Let's continue in #157 since now it sounds like it might be highly relevant.
