### ISSUE TITLE
framework not found CocoaAsyncSocket

### ISSUE THREAD

**Issue by SerggioC** [rabbitmq/rabbitmq-objc-client#169]
How do I solve this issue? I keep getting this error when trying to build the project with this pod dependency.

framework not found CocoaAsyncSocket

**Comment by lukebakken** [comment]
Hello. Thanks for using this library. In the future, please ask questions on the [`rabbitmq-users`](https://groups.google.com/forum/#!forum/rabbitmq-users) mailing list.

I searched google for `framework not found CocoaAsyncSocket` and [this](https://github.com/robbiehanson/XMPPFramework/issues/660) is the first hit. Presumably it will fix your issue.

**Comment by michaelklishin** [comment]
Another possible reason is that [Carthage bootstrap](https://github.com/rabbitmq/rabbitmq-objc-client/blob/master/CONTRIBUTING.md) has never been performed.
