### ISSUE TITLE
Client sends regular heartbeat negotiated with server

### ISSUE THREAD

**Issue by camelpunch** [rabbitmq/rabbitmq-objc-client#17]

**Comment by michaelklishin** [comment]
Heartbeat interval is [negotiated between client and server](https://groups.google.com/forum/#!searchin/rabbitmq-users/heartbeat$20negotiation/rabbitmq-users/FpUdTaIr8CI/DYlfnxwXFAAJ).

**Comment by camelpunch** [comment]
Yes. I saw the negotiation happening in Bunny. Is that implementation sufficient?

**Comment by michaelklishin** [comment]
Bunny should do the same thing as Java client.

**Comment by michaelklishin** [comment]
Note that what is called "heartbeat interval" is actually "heartbeat timeout" in some clients, for historical reasons. I'd recommend copying what Java client and Bunny do.

**Comment by kjnilsson** [comment]
tested.
