### ISSUE TITLE
RMQClient issues with Cocoapods

### ISSUE THREAD

**Issue by DntPullALockett** [rabbitmq/rabbitmq-objc-client#176]
**Issue**: Cocoapods install fails vs Carthage working fine

Example: I have an application that used to use Carthage. We use the following dependencies locked to the various versions

github "jeffh/JKVValue" "v1.3.3"
github "rabbitmq/rabbitmq-objc-client" "v0.10.0"
github "robbiehanson/CocoaAsyncSocket" "7.6.3"

This works fine. 

Now we wanted to switch over to use Cocoapods and setup the Podfile using those same versions

  pod 'JKVValue', '~> 1.3.3'
  pod 'RMQClient', '0.10.0'
  pod 'CocoaAsyncSocket', '7.6.3'

When running a pod install we would get the following error:

`!] CocoaPods could not find compatible versions for pod "CocoaAsyncSocket":
  In snapshot (Podfile.lock):
    CocoaAsyncSocket (= 7.6.3, ~> 7.4)

  In Podfile:
    CocoaAsyncSocket (= 7.6.3)

    RMQClient (= 0.10.0) was resolved to 0.10.0, which depends on
      CocoaAsyncSocket (~> 7.4.0)

Specs satisfying the `CocoaAsyncSocket (= 7.6.3), CocoaAsyncSocket (= 7.6.3, ~> 7.4), CocoaAsyncSocket (~> 7.4.0)` dependency were found, but they required a higher minimum deployment target.`

**Research**: We started to do some research into what was different. 

First we tested pod version 0.9.0 and noticed this installed fine with CocoaAsyncSocket 7.6.3. from here we started to understand what was different between the 0.9.0 and 0.10.0 podspec files for RMQClient

We noticed that the CocoAsyncSocket dependency states version 7.4 on 0.9.0 and 7.4.0 on 0.10.0 the 7.4.0 does not exist as a release, when I changed this locally in my pod spec repo to 7.4 it installed correctly with no error.

**Proposed Resolution**: Can you look into this issue for the version 0.10.0 and see if updating the CocoaAsyncSocket to 7.4 instead of 7.4.0 is a good working solution. Updating our pod to the most recents provide at least a month of work for us to change and update the code.

**Comment by michaelklishin** [comment]
`v0.10.0` has already been tagged. I will bump the dependency as producing a CocoaPods release is a pending item anyway.

**Comment by michaelklishin** [comment]
The dependency has been bumped to `7.6.4` in master. I will switch to `~> 7.6` as CocoaPods installation instructions, in fact, suggest.

**Comment by michaelklishin** [comment]
`0.11.0-rc2` is [published](https://cocoapods.org/pods/RMQClient). Please give it a shot and if it works well for the community, I will cut a final release.
