### ISSUE TITLE
Can this library support ios9+

### ISSUE THREAD

**Issue by duxiaoyan** [rabbitmq/rabbitmq-objc-client#183]
Hello，you descrided this library currently targets iOS 11+ and macOS 10.12+， but  my app need support ios9+，will there be any problems if I continue to use it？
Thanks！

**Comment by michaelklishin** [comment]
I will convert this issue to a GitHub discussion. Currently GitHub will [automatically close and lock the issue](https://github.com/github/feedback/discussions/3197) even though your question will be transferred and responded to elsewhere. This is to let you know that we do not intend to ignore this but this is how the current GitHub conversion mechanism makes it seem for the users :(
