### ISSUE TITLE
Crash while getting allocatedUserChannels

### ISSUE THREAD

**Issue by jackkudo** [rabbitmq/rabbitmq-objc-client#236]
### Describe the bug

In some cases the app crashes. I got the log from the Test Flight then saw the issue come from the function 
- (NSArray *)allocatedUserChannels in class RMQMultipleChannelAllocator.m

Seems like in that function it tried to remove the first element in case the array is empty.

### Reproduction steps

No specific steps. Sometimes it happens.

### Expected behavior

Must check the array length should be greater than 0 then remove the first element as the current logic.

### Additional context

<img width="1512" alt="Screenshot 2024-10-09 at 16 14 30" src="https://github.com/user-attachments/assets/1a2adeff-c4f8-4be0-bf71-c56a50c708be">

**Comment by michaelklishin** [comment]
A fix was contributed by @jackkudo in #237.

**Comment by jackkudo** [comment]
Hi @michaelklishin Can you release a new version for this fix?

**Comment by michaelklishin** [comment]
@jackkudo I can tag a new version later this week if that's what you mean.

**Comment by jackkudo** [comment]
Yes. That's good. Because now our application it crashes sometimes.

Thanks in advance!
@michaelklishin

**Comment by michaelklishin** [comment]
@jackkudo [done](https://github.com/rabbitmq/rabbitmq-objc-client/releases/tag/v0.13.0).

If you'd like to help maintain this project, I'd appreciate some input on https://github.com/rabbitmq/rabbitmq-objc-client/issues/231. We don't have to use Carthage the same way we do (or at all), of course.

And I'd be happy to grant you push permissions to this repo if you have some cycles to help. For many years now my focus is almost entirely on RabbitMQ itself, not so much on client libraries.

**Comment by jackkudo** [comment]
@michaelklishin  Thank you.

I didn't see the new version while fetching via CocoaPods. Can you check why?

**Comment by michaelklishin** [comment]
Because I have only tagged this release. I haven't done a CocoaPods release in 18 months so it will take a bit of time to figure out how that's done today, and if the build system even can accommodate a proper release.

**Comment by jackkudo** [comment]
Yes. No problem. I can wait even in next week to have a new version in CocoaPods. Can you do it?

**Comment by michaelklishin** [comment]
@jackkudo like I said, I do not work on iOS or macOS projects so it takes me a long time to figure out things such as [this one](https://stackoverflow.com/questions/77139617/clang-error-sdk-does-not-contain-libarclite-at-the-path) (which is an error that prevents `pod lib lint` and `pod trunk push` from succeeding right now).

**Comment by jackkudo** [comment]
Ah ok. So is there any way that I can update the latest version without CocoaPods?

**Comment by jackkudo** [comment]
Hi @michaelklishin  I found an alternative way to fetch the latest of RabbitMQ by CocoaPods. Using this line
pod 'RMQClient', :git => 'https://github.com/rabbitmq/rabbitmq-objc-client.git' instead of 
pod 'RMQClient'

And now it works.
So, you don't need to care about the issue above.

**Comment by michaelklishin** [comment]
@jackkudo it's great that `Podfile` allows you to specify a git dependency but as a library maintainer, I cannot just ignore the fact that publishing of new versions is currently broken.

**Comment by jackkudo** [comment]
@michaelklishin I know. I'll check your issue when I have time.
