### ISSUE TITLE
Can sometimes 'lose' a consumer when playing with tutorial 1

### ISSUE THREAD

**Issue by camelpunch** [rabbitmq/rabbitmq-objc-client#70]
Consumer block is not fired sometimes after running tutorial 1 with just the receive method enabled. Messages from e.g. Bunny or management UI don't get processed by the handler block, though the messages do get removed from the queue.

**Comment by dumbbell** [comment]
Such messages are actually delivered to the ObjectiveC client, according to Wireshark. I don't know however if they are being read from the network or not.

**Comment by camelpunch** [comment]
Fix is in https://github.com/rabbitmq/rabbitmq-objc-client/commit/97d69fc048f06b6444c3ea94eea3d991c2bc7066
