### ISSUE TITLE
Where is the API document？

### ISSUE THREAD

**Issue by zsw839129740** [rabbitmq/rabbitmq-objc-client#77]
Without API documentation,I will not use.

**Comment by camelpunch** [comment]
There's auto-generated 'API documentation' at http://cocoadocs.org/docsets/RMQClient/ but we haven't yet added descriptions of methods. You can start to learn how to use the framework at https://www.rabbitmq.com/tutorials/tutorial-one-objectivec.html in the meantime.

Is there anything I can help you with before we flesh out the API documentation?

**Comment by zsw839129740** [comment]
Thank you very much.I'll learn about it first.

**Comment by zsw839129740** [comment]
How to connect a user name and password of the rabbitmq server?
Is it using RMQConnection?
Can provide examples?

**Comment by camelpunch** [comment]
Username and password is set in the URI. I've added a Usage section with an
example: https://github.com/rabbitmq/rabbitmq-objc-client#usage
