### ISSUE TITLE
Accessing RMQMessage properties

### ISSUE THREAD

**Issue by hasbean** [rabbitmq/rabbitmq-objc-client#80]
I need to access the correlationID of an incoming message, but for some reason it's missing from the header file.

I added this to RMQMessage.h 

```
@property (nonatomic, readonly) NSArray *properties;
```
Works great so far.

**Comment by camelpunch** [comment]
I have a part-finished addition to Michael's commits that gives easier access via convenience methods.

**Comment by camelpunch** [comment]
Re-opening until aforementioned convenience work is in master.
